# Generated by Django 5.1.3 on 2024-11-20 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citizens', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='citizen',
            name='birth_date',
        ),
        migrations.RemoveField(
            model_name='citizen',
            name='citizen_id',
        ),
        migrations.AddField(
            model_name='citizen',
            name='middle_name',
            field=models.CharField(blank=True, default='Unknown', max_length=100),
        ),
    ]
