# Generated by Django 5.1.3 on 2024-11-19 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hash_pan', models.CharField(max_length=64)),
                ('transaction_time', models.DateTimeField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('terminal_id', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('SUCCESS', 'Successful'), ('FAILED', 'Failed'), ('DISCOUNT_ERROR', 'Discount Error')], default='SUCCESS', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
